# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://netlify-cms-react-starter.netlify.com # This url will display in the top-right of the CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Page"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: "content/pages/contact.md"
        label: "Contact Page"
        name: "contact-page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Featured Image, name: featuredImage, widget: image}
          - {label: Subtitle, name: subtitle, widget: markdown}
          - {label: Body, name: body, widget: markdown}
          - {label: Address, name: address, widget: text}
          - {label: Phone, name: phone, widget: string}
          - {label: Email Address, name: email, widget: string}
          - label: "Meta"
            required: false
            name: "meta"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
              - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
              - {label: Noindex, name: noindex, widget: boolean, required: false}

      - file: "content/pages/blog.md"
        label: "Blog Page"
        name: "blog-page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Featured Image, name: featuredImage, widget: image}
          - {label: Subtitle, name: subtitle, widget: markdown}
          - label: "Meta"
            required: false
            name: "meta"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
              - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
              - {label: Noindex, name: noindex, widget: boolean, required: false}

      - file: "content/pages/resume.md"
        label: "Resume Page"
        name: "resume-page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: markdown}
          - {label: Intro, name: intro, widget: markdown}
          - label: "Meta"
            required: false
            name: "meta"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
              - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
              - {label: Noindex, name: noindex, widget: boolean, required: false}

      - file: "content/pages/home.md"
        label: "Home Page"
        name: "home-page"
        fields:
          - label: "About"
            required: false
            name: about
            widget: "object"
            fields:
                - {label: Title, name: title, widget: string, required: true}
                - {label: Intro, name: intro, widget: markdown}
                - label: "Blurb 1"
                  name: "blurb-1"
                  widget: "object"
                  fields:
                      - {label: Title, name: title, widget: string}
                      - {label: Icon, name: Icon, widget: select, options: ["code","edit-2","trash-2"]}
                      - {label: Description, name: description, widget: markdown}
                - label: "Blurb 2"
                  name: "blurb-2"
                  widget: "object"
                  fields:
                      - {label: Title, name: title, widget: string}
                      - {label: Icon, name: Icon, widget: select, options: ["code","edit-2","trash-2"]}
                      - {label: Description, name: description, widget: markdown}
                - label: "Blurb 3"
                  name: "blurb-3"
                  widget: "object"
                  fields:
                      - {label: Title, name: title, widget: string}
                      - {label: Icon, name: Icon, widget: select, options: ["code","edit-2","trash-2"]}
                      - {label: Description, name: description, widget: markdown}
          - label: "Attributes"
            name: "attributes"
            widget: "object"
            fields:
                - {label: Status, name: status, widget: string}
                - {label: Favourite Thing, name: favouriteThing, widget: string}
                - {label: Job Type, name: jobType, widget: string}
                - {label: Mobility, name: mobility, widget: string}
                - {label: Position, name: position, widget: string}
                - {label: Industry, name: industry, widget: string}

          - label: "Featured Employment"
            name: "featuredEmployment"
            widget: "list"
            fields:
              - label: "Job"
                name: "job"
                widget: "relation"
                collection: "employment"
                searchFields: ["key","title"]
                valueField: "key"
                displayFields: ["title"]

          - label: "Featured Skills"
            name: "featuredSkills"
            widget: "list"
            fields:
              - label: "Skill"
                name: "skill"
                widget: "relation"
                collection: "professionalSkills"
                searchFields: ["key","title"]
                valueField: "key"
                displayFields: ["title"]

          - label: "Meta"
            required: false
            name: "meta"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
              - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
              - {label: Noindex, name: noindex, widget: boolean, required: false}


  - name: posts
    label: Post
    editor:
      preview: true
    folder: content/posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ["Published", "Featured", "Draft"]
        default: 'Published'
      - {label: Date / Order, name: date, widget: date}
      - {label: Post Featured Image, name: postFeaturedImage, widget: image, required: false}
      - {label: Excerpt, name: excerpt, widget: text}
      - {label: Content, name: body, widget: markdown}
      - label: "Categories"
        name: "categories"
        widget: "list"
        required: false
        fields:
          - label: "Category"
            name: "category"
            widget: "relation"
            collection: "postCategories"
            searchFields: ["title"]
            valueField: "title"
      - label: "Meta"
        required: false
        name: "meta"
        widget: "object"
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
          - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
          - {label: Noindex, name: noindex, widget: boolean, required: false}


  - name: postCategories
    label: Post Category
    editor:
      preview: false
    folder: content/postCategories
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - label: "Meta"
        required: false
        name: "meta"
        widget: "object"
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
          - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
          - {label: Noindex, name: noindex, widget: boolean, required: false}

  - name: "profileCard"
    label: "Profile Card"
    delete: false
    editor:
      preview: false
    files:
      - file: "content/profileCard/data.yml"
        label: "Data"
        name: "data"
        fields:
          - {label: Full Name, name: fullName, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Display Image, name: displayImage, widget: image}

  - name: "employment"
    label: "Employment"
    slug: "{{slug}}"
    editor:
      preview: false
    folder: content/employment
    create: true
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Key, name: key, widget: string, required: true}
      - {label: Position, name: position, widget: string, required: true}
      - {label: Image, name: image, widget: image, default: /images/logo.png}
      - {label: Start Date, name: startDate, widget: date}
      - {label: End Date, name: endDate, widget: date, required: false}
      - {label: Description, name: description, widget: markdown}

  - name: "education"
    label: "Education"
    slug: "{{slug}}"
    editor:
      preview: false
    folder: content/education
    create: true
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Key, name: key, widget: string, required: true}
      - {label: Course, name: course, widget: string, required: true}
      - {label: Degree, name: degree, widget: string}
      - {label: Image, name: image, widget: image, default: /images/logo.png}
      - {label: Start Date, name: startDate, widget: date}
      - {label: End Date, name: endDate, widget: date, required: false}
      - {label: Description, name: description, widget: markdown}

  - name: "professionalSkills"
    label: "Professional Skills"
    slug: "{{slug}}"
    editor:
      preview: false
    folder: content/professionalSkills
    create: true
    fields:
      - {label: title, name: title, widget: string, required: true}
      - {label: Key, name: key, widget: string, required: true}
      - {label: Years of Experience, name: yearsOfExperience, widget: number, valueType: float}
      - {label: Skill Level, name: skillLevel, widget: number, valueType: float, min: 0, max: 100}
      - {label: Image, name: image, widget: image, default: /images/logo.png}
      - {label: Description, name: description, widget: markdown}
  - name: "projects"
    label: "Projects"
    slug: "{{slug}}"
    editor:
      preview: false
    folder: content/projects
    create: true
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Image, name: image, widget: image, default: /images/logo.png}
      - {label: Hero Image, name: heroImage, widget: image, default: /images/logo.png}
      - {label: key, name: key, widget: string, required: true}
      - {label: Detail, name: detail, widget: markdown}
      - label: "Skills Used"
        name: "skillsUsed"
        widget: "list"
        fields:
          - label: "Skill"
            name: "skill"
            widget: "relation"
            collection: "professionalSkills"
            searchFields: ["title", "key"]
            valueField: "key"


  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Url, name: siteUrl, widget: string, required: false}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - {label: Image, name: image, widget: image, required: false}
              - {label: Twitter Site Account, name: twitterSiteAccount, widget: string, required: false}
              - {label: Twitter Creator Account, name: twitterCreatorAccount, widget: string, required: false}
          - {label: Header Meta / Scripts, name: headerScripts, widget: text, required: false}
          - {label: Enable Service Worker Pre-Cache, name: enableServiceWorker, widget: boolean, required: false}
